### ISSUE TITLE
Can you provide a grey Orange theme

### ISSUE THREAD

**Issue by jahnli** [alexTitakoff/vscode-intellij-idea-light-theme#1]
Can you provide a grey Orange theme
[grey_orange.zip](https://github.com/alexTitakoff/vscode-intellij-idea-light-theme/files/5382174/grey_orange.zip)

**Comment by alexTitakoff** [comment]
Can try.
Where can I launch this theme?
I didn't find where ".icls" format is used.

**Comment by alexTitakoff** [comment]
I understand, how to start it.

I  may be can do this, but the theme itself is dark.
It is better to do it separately. It makes more sense. 
I have only light information in my package.

I'm sorry, but I won't do this. 
I made this theme because I use it and I like it.

Grey orange theme I'm not sure what I'll use.  : ||

**Comment by jahnli** [comment]
Icls just import the theme on WebStorm, you can try it, if you really like it

**Comment by alexTitakoff** [comment]
Unfortunately, this will take a long time.
There are quite a few good dark themes.

Orange
https://github.com/raxjs/rax-vscode-extensions
Standard Dracula for example.
https://github.com/kevinvn1709/vscode-dracula-color-theme

If you want to make a theme to match your colors, I can send you good guides.
